#pragma once

//#define NO_KEYBOARD


// activate keys to accept input from
#define KEYBOARD_A 1
#define KEYBOARD_B 1
#define KEYBOARD_C 0
#define KEYBOARD_D 1
#define KEYBOARD_E 0
#define KEYBOARD_F 0
#define KEYBOARD_G 1
#define KEYBOARD_H 0
#define KEYBOARD_I 0
#define KEYBOARD_J 0
#define KEYBOARD_K 0
#define KEYBOARD_L 0
#define KEYBOARD_M 0
#define KEYBOARD_N 0
#define KEYBOARD_O 0
#define KEYBOARD_P 1
#define KEYBOARD_Q 0
#define KEYBOARD_R 1
#define KEYBOARD_S 1
#define KEYBOARD_T 0
#define KEYBOARD_U 0
#define KEYBOARD_V 0
#define KEYBOARD_W 1
#define KEYBOARD_X 0
#define KEYBOARD_Y 0
#define KEYBOARD_Z 0
#define KEYBOARD_0 0
#define KEYBOARD_1 1
#define KEYBOARD_2 1
#define KEYBOARD_3 1
#define KEYBOARD_4 1
#define KEYBOARD_5 0
#define KEYBOARD_6 0
#define KEYBOARD_7 0
#define KEYBOARD_8 0
#define KEYBOARD_9 0
#define KEYBOARD_UP 1
#define KEYBOARD_DOWN 1
#define KEYBOARD_LEFT 1
#define KEYBOARD_RIGHT 1
#define KEYBOARD_RETURN 1
#define KEYBOARD_ESCAPE 0
#define KEYBOARD_SPACE 1
#define KEYBOARD_LSHIFT 0
#define KEYBOARD_RSHIFT 0
#define KEYBOARD_NUMPAD_0 0
#define KEYBOARD_NUMPAD_1 0
#define KEYBOARD_NUMPAD_2 0
#define KEYBOARD_NUMPAD_3 0
#define KEYBOARD_NUMPAD_4 0
#define KEYBOARD_NUMPAD_5 0
#define KEYBOARD_NUMPAD_6 0
#define KEYBOARD_NUMPAD_7 0
#define KEYBOARD_NUMPAD_8 0
#define KEYBOARD_NUMPAD_9 0
#define KEYBOARD_NUMPAD_PLUS 0
#define KEYBOARD_NUMPAD_MINUS 0
#define KEYBOARD_NUMPAD_MULTIPLY 0
#define KEYBOARD_NUMPAD_DIVIDE 0
#define KEYBOARD_CTRL 1


namespace input
{
#ifdef NO_KEYBOARD
	constexpr unsigned N_KEYBOARD_KEYS = 0;
#else

	constexpr unsigned N_KEYBOARD_KEYS = 
	KEYBOARD_A + 
	KEYBOARD_B + 
	KEYBOARD_C + 
	KEYBOARD_D + 
	KEYBOARD_E + 
	KEYBOARD_F + 
	KEYBOARD_G + 
	KEYBOARD_H + 
	KEYBOARD_I + 
	KEYBOARD_J + 
	KEYBOARD_K + 
	KEYBOARD_L + 
	KEYBOARD_M + 
	KEYBOARD_N + 
	KEYBOARD_O + 
	KEYBOARD_P + 
	KEYBOARD_Q + 
	KEYBOARD_R + 
	KEYBOARD_S + 
	KEYBOARD_T + 
	KEYBOARD_U + 
	KEYBOARD_V + 
	KEYBOARD_W + 
	KEYBOARD_X + 
	KEYBOARD_Y + 
	KEYBOARD_Z + 
	KEYBOARD_0 + 
	KEYBOARD_1 + 
	KEYBOARD_2 + 
	KEYBOARD_3 + 
	KEYBOARD_4 + 
	KEYBOARD_5 + 
	KEYBOARD_6 + 
	KEYBOARD_7 + 
	KEYBOARD_8 + 
	KEYBOARD_9 + 
	KEYBOARD_UP + 
	KEYBOARD_DOWN + 
	KEYBOARD_LEFT + 
	KEYBOARD_RIGHT + 
	KEYBOARD_RETURN + 
	KEYBOARD_ESCAPE + 
	KEYBOARD_SPACE + 
	KEYBOARD_LSHIFT +
	KEYBOARD_RSHIFT +
	KEYBOARD_NUMPAD_0 +
	KEYBOARD_NUMPAD_1 +
	KEYBOARD_NUMPAD_2 +
	KEYBOARD_NUMPAD_3 +
	KEYBOARD_NUMPAD_4 +
	KEYBOARD_NUMPAD_5 +
	KEYBOARD_NUMPAD_6 +
	KEYBOARD_NUMPAD_7 +
	KEYBOARD_NUMPAD_8 +
	KEYBOARD_NUMPAD_9 +
	KEYBOARD_NUMPAD_PLUS + 
	KEYBOARD_NUMPAD_MINUS + 
	KEYBOARD_NUMPAD_MULTIPLY + 
	KEYBOARD_NUMPAD_DIVIDE +
	KEYBOARD_CTRL;

#endif
}
