#pragma once

//#define NO_GAMEPAD
//#define SINGLE_GAMEPAD


#define GAMEPAD_BTN_DPAD_UP 1
#define GAMEPAD_BTN_DPAD_DOWN 1
#define GAMEPAD_BTN_DPAD_LEFT 1
#define GAMEPAD_BTN_DPAD_RIGHT 1
#define GAMEPAD_BTN_START 1
#define GAMEPAD_BTN_BACK 1
#define GAMEPAD_BTN_SOUTH 1
#define GAMEPAD_BTN_EAST 1
#define GAMEPAD_BTN_WEST 1
#define GAMEPAD_BTN_NORTH 1
#define GAMEPAD_BTN_SHOULDER_LEFT 1
#define GAMEPAD_BTN_SHOULDER_RIGHT 1
#define GAMEPAD_BTN_STICK_LEFT 1
#define GAMEPAD_BTN_STICK_RIGHT 1
#define GAMEPAD_AXIS_STICK_LEFT 1
#define GAMEPAD_AXIS_STICK_RIGHT 1
#define GAMEPAD_TRIGGER_LEFT 1
#define GAMEPAD_TRIGGER_RIGHT 1

#if GAMEPAD_BTN_DPAD_UP && GAMEPAD_BTN_DPAD_DOWN && GAMEPAD_BTN_DPAD_LEFT && GAMEPAD_BTN_DPAD_RIGHT
#define GAMEPAD_BTN_DPAD_ALL 1
#else
#define GAMEPAD_BTN_DPAD_ALL 0
#endif




namespace input
{
#ifdef NO_GAMEPAD
    constexpr unsigned N_GAMEPAD_BUTTONS = 0;
    constexpr unsigned N_GAMEPAD_AXES = 0;
#else

    constexpr unsigned N_GAMEPAD_BUTTONS = 
    GAMEPAD_BTN_DPAD_UP +
    GAMEPAD_BTN_DPAD_DOWN +
    GAMEPAD_BTN_DPAD_LEFT +
    GAMEPAD_BTN_DPAD_RIGHT +
    GAMEPAD_BTN_START +
    GAMEPAD_BTN_BACK +    
    GAMEPAD_BTN_SOUTH +
    GAMEPAD_BTN_EAST +
    GAMEPAD_BTN_WEST +
    GAMEPAD_BTN_NORTH +
    GAMEPAD_BTN_SHOULDER_LEFT +
    GAMEPAD_BTN_SHOULDER_RIGHT +
    GAMEPAD_BTN_STICK_LEFT +
    GAMEPAD_BTN_STICK_RIGHT;

    constexpr unsigned N_GAMEPAD_AXES =
    GAMEPAD_AXIS_STICK_LEFT +
    GAMEPAD_AXIS_STICK_RIGHT +
    GAMEPAD_TRIGGER_LEFT +
    GAMEPAD_TRIGGER_RIGHT;

#endif
}
