#pragma once

#define JOYSTICK_BTN_0 1
#define JOYSTICK_BTN_1 1
#define JOYSTICK_BTN_2 1
#define JOYSTICK_BTN_3 1
#define JOYSTICK_BTN_4 1
#define JOYSTICK_BTN_5 1
#define JOYSTICK_BTN_6 1
#define JOYSTICK_BTN_7 1
#define JOYSTICK_BTN_8 1
#define JOYSTICK_BTN_9 1
#define JOYSTICK_AXIS_STICK_LEFT 1
#define JOYSTICK_AXIS_STICK_RIGHT 1


namespace input
{
    constexpr unsigned N_JOYSTICK_BUTTONS = 
    JOYSTICK_BTN_0 +
    JOYSTICK_BTN_1 +
    JOYSTICK_BTN_2 +
    JOYSTICK_BTN_3 +
    JOYSTICK_BTN_4 +
    JOYSTICK_BTN_5 +
    JOYSTICK_BTN_6 +
    JOYSTICK_BTN_7 +
    JOYSTICK_BTN_8 +
    JOYSTICK_BTN_9;
}